source 'https://rubygems.org'
gem 'jekyll', '2.4.0'
gem 'github-pages'
gem 'rouge'
gem 'jekyll-redirect-from'
gem 'ffi', :git => 'git://github.com/ffi/ffi.git', :branch => 'elcapt'
gem 'html-proofer'
